config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # get 'deadpool/home'
  # get 'sourav',to: 'deadpool#about'
  # get 'deadpool/download'

  root 'tweets#index'

  # registrations routes
  get 'signup', to:'registrations#new'
  post 'signup', to:'registrations#create'

  # logout routes
  delete 'logout', to:'sessions#destroy'

  #login routes

  get 'login',to:'sessions#new'
  post 'login',to:'sessions#create'

  #edit password
  get 'password', to:'passwords#edit',as: :edit_password # for showing password edit field
  patch 'password', to:'passwords#update' # for updating the password


  #password reset urls
  get 'password/reset', to:'password_resets#new'
  post 'password/reset', to:'password_resets#create'

  get 'password/reset/edit', to:'password_resets#edit'
  patch 'password/reset/edit', to:'password_resets#update'

  # routes for MyTweets
  get 'mytweets',to:'mains#my_tweets'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crud.rb
class Crud < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
	# has_secure_password
	attribute :reg
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	# comment
end

app/models/registration.rb
class Registration < ApplicationRecord
	has_many :tweets
	has_secure_password

	validates :name, presence: true ,length: {in:5..30,message:" must be in 5-30 charector"}
	validates :email, presence: true , format:{with:/^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i , message: "Must be a valid email",:multiline => true }

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :registration
end

app/models/user.rb
class User < ApplicationRecord
	# validates :name, presence: true,:message=>"Enter name pls"
	# validates_presence_of :name, message:"Entr name"
	us=User.find_by(name:"Toton")
	# us.name="Deadpool"
	# us.save
	us.update(bio:"ruby on rails coder")


	def is_cool
		# puts"#{self.name} is cool for his age #{self.age}"
		self.name.to_s+" is cool"
	end

	def info
		self.name+" "+ self.bio
	end
end

app/controllers/crud_controller.rb
class CrudController < ApplicationController
  def index
  	@names=Crud.all

  end
  def new
  	@name=Crud.new


  end
  def create
  	@name=Crud.new(crud_param)
  	if @name.save
  		redirect_to index_path
  	end

  end
  def destroy

  end
  def update

  end
  def show

  end
  private
  	def crud_param
  		params.require(:name).permit(:name,:title,:age)
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about
  end
  def contact
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
	before_action :loggedin?
	def index
		# if session[:id]
		# 	@reg=Registration.find_by(id:session[:id])

		# end
	end
	def my_tweets
		@MyTweets=Current.reg.tweets
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crud_helper.rb
module CrudHelper
end

app/helpers/deadpool_helper.rb
module DeadpoolHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/mains/index.html.erb
<% if notice %>
	<div class="alert alert-warning alert-dismissible fade show m-4" role="alert">
	  	<%= notice %>
	 <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>

<% end %>

<h1 class="m-4 text-center"> This is Root </h1>

<% if Current.reg %>
	<h2 class="ms-4 text-center">You are logged in as <%= Current.reg.name %> </h2>
	<div class="text-center mt-2">
		
	<%= link_to "Logout",logout_path,method: :delete,data:{confirm:"are you sure"},class:'btn btn-dark ms-4'  %>
	</div>
<% end %>

app/views/mains/my_tweets.html.erb
<h1>You have <%= pluralize(@MyTweets.count,'tweet') %> </h1>

<% @MyTweets.each do |tweet| %>
  <h2><%= tweet.title %></h2>
  <p><%= tweet.body %></p>
  <%= link_to "Show", tweet_path(tweet.id) %>
  <%= link_to "Edit", edit_tweet_path(tweet.id) %>
  <%= link_to "Delete", tweet_path(tweet.id) ,method: :delete,data: { confirm: 'You can get this back do want to relly delete this?'}%>
  <hr>
<% end %>